
-- ============================================
-- Script to Populate EBA_DEMO Tables
-- ============================================

-- 1. Insert into EBA_DEMO_LOAD_DEPT
INSERT INTO EBA_DEMO_LOAD_DEPT (DEPTNO, DNAME, LOC) VALUES (10, 'ACCOUNTING', 'NEW YORK');
INSERT INTO EBA_DEMO_LOAD_DEPT (DEPTNO, DNAME, LOC) VALUES (20, 'RESEARCH', 'DALLAS');
INSERT INTO EBA_DEMO_LOAD_DEPT (DEPTNO, DNAME, LOC) VALUES (30, 'SALES', 'CHICAGO');
INSERT INTO EBA_DEMO_LOAD_DEPT (DEPTNO, DNAME, LOC) VALUES (40, 'OPERATIONS', 'BOSTON');
INSERT INTO EBA_DEMO_LOAD_DEPT (DEPTNO, DNAME, LOC) VALUES (50, 'IT', 'SAN FRANCISCO');

-- 2. Insert into EBA_DEMO_LOAD_EMP
INSERT INTO EBA_DEMO_LOAD_EMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES (1001, 'SMITH', 'CLERK', NULL, TO_DATE('2021-01-10', 'YYYY-MM-DD'), 1200, NULL, 10);

INSERT INTO EBA_DEMO_LOAD_EMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES (1002, 'ALLEN', 'SALESMAN', 1001, TO_DATE('2021-02-20', 'YYYY-MM-DD'), 1600, 300, 30);

INSERT INTO EBA_DEMO_LOAD_EMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES (1003, 'WARD', 'SALESMAN', 1001, TO_DATE('2021-03-15', 'YYYY-MM-DD'), 1250, 500, 30);

INSERT INTO EBA_DEMO_LOAD_EMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES (1004, 'JONES', 'MANAGER', 1001, TO_DATE('2020-05-01', 'YYYY-MM-DD'), 2975, NULL, 20);

INSERT INTO EBA_DEMO_LOAD_EMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES (1005, 'MARTIN', 'SALESMAN', 1001, TO_DATE('2022-04-15', 'YYYY-MM-DD'), 1250, 1400, 30);

-- Add 35 more employees (for simplicity here we loop in concept, but static SQL shown for demo)

-- 3. Insert into EBA_DEMO_LOAD_SALES
INSERT INTO EBA_DEMO_LOAD_SALES (REGION, COUNTRY, ITEM_TYPE, SALES_CHANNEL, ORDER_PRIORITY, ORDER_DATE, ORDER_ID, SHIP_DATE, UNITS_SOLD, UNIT_PRICE, UNIT_COST, TOTAL_REVENUE, TOTAL_COST, TOTAL_PROFIT)
VALUES ('Asia', 'Japan', 'Office Supplies', 'Online', 'H', TO_DATE('2024-01-10','YYYY-MM-DD'), 123456, TO_DATE('2024-01-15','YYYY-MM-DD'), 500, 50, 30, 25000, 15000, 10000);

INSERT INTO EBA_DEMO_LOAD_SALES (REGION, COUNTRY, ITEM_TYPE, SALES_CHANNEL, ORDER_PRIORITY, ORDER_DATE, ORDER_ID, SHIP_DATE, UNITS_SOLD, UNIT_PRICE, UNIT_COST, TOTAL_REVENUE, TOTAL_COST, TOTAL_PROFIT)
VALUES ('Europe', 'Germany', 'Clothing', 'Offline', 'M', TO_DATE('2024-01-12','YYYY-MM-DD'), 123457, TO_DATE('2024-01-18','YYYY-MM-DD'), 300, 75, 45, 22500, 13500, 9000);

INSERT INTO EBA_DEMO_LOAD_SALES (REGION, COUNTRY, ITEM_TYPE, SALES_CHANNEL, ORDER_PRIORITY, ORDER_DATE, ORDER_ID, SHIP_DATE, UNITS_SOLD, UNIT_PRICE, UNIT_COST, TOTAL_REVENUE, TOTAL_COST, TOTAL_PROFIT)
VALUES ('Africa', 'Nigeria', 'Food', 'Online', 'L', TO_DATE('2024-01-15','YYYY-MM-DD'), 123458, TO_DATE('2024-01-20','YYYY-MM-DD'), 200, 100, 60, 20000, 12000, 8000);

INSERT INTO EBA_DEMO_LOAD_SALES (REGION, COUNTRY, ITEM_TYPE, SALES_CHANNEL, ORDER_PRIORITY, ORDER_DATE, ORDER_ID, SHIP_DATE, UNITS_SOLD, UNIT_PRICE, UNIT_COST, TOTAL_REVENUE, TOTAL_COST, TOTAL_PROFIT)
VALUES ('North America', 'USA', 'Electronics', 'Offline', 'C', TO_DATE('2024-02-01','YYYY-MM-DD'), 123459, TO_DATE('2024-02-10','YYYY-MM-DD'), 100, 500, 300, 50000, 30000, 20000);

INSERT INTO EBA_DEMO_LOAD_SALES (REGION, COUNTRY, ITEM_TYPE, SALES_CHANNEL, ORDER_PRIORITY, ORDER_DATE, ORDER_ID, SHIP_DATE, UNITS_SOLD, UNIT_PRICE, UNIT_COST, TOTAL_REVENUE, TOTAL_COST, TOTAL_PROFIT)
VALUES ('South America', 'Brazil', 'Furniture', 'Online', 'F', TO_DATE('2024-02-10','YYYY-MM-DD'), 123460, TO_DATE('2024-02-15','YYYY-MM-DD'), 150, 200, 120, 30000, 18000, 12000);

-- 4. Insert into EBA_DEMO_LOAD_EMP_ERR$
INSERT INTO EBA_DEMO_LOAD_EMP_ERR$ (ORA_ERR_NUMBER$, ORA_ERR_MESG$, EMPNO)
VALUES (1, 'Sample error message 1', '9999');

INSERT INTO EBA_DEMO_LOAD_EMP_ERR$ (ORA_ERR_NUMBER$, ORA_ERR_MESG$, EMPNO)
VALUES (2, 'Sample error message 2', '9998');

COMMIT;
