INSERT INTO EBA_DEMO_MERCHANDISE (NAME, DESCRIPTION) VALUES ('T-Shirt', 'High-quality cotton t-shirt');
INSERT INTO EBA_DEMO_MERCHANDISE (NAME, DESCRIPTION) VALUES ('Mug', 'Ceramic coffee mug with logo');
INSERT INTO EBA_DEMO_MERCHANDISE (NAME, DESCRIPTION) VALUES ('Notebook', 'A5 size spiral notebook');
INSERT INTO EBA_DEMO_MERCHANDISE (NAME, DESCRIPTION) VALUES ('Backpack', 'Durable laptop backpack');
INSERT INTO EBA_DEMO_MERCHANDISE (NAME, DESCRIPTION) VALUES ('Water Bottle', '500ml insulated water bottle');
INSERT INTO EBA_DEMO_MERCHANDISE (NAME, DESCRIPTION) VALUES ('Cap', 'Adjustable baseball cap');
INSERT INTO EBA_DEMO_MERCHANDISE (NAME, DESCRIPTION) VALUES ('Keychain', 'Metal keychain with logo');
INSERT INTO EBA_DEMO_MERCHANDISE (NAME, DESCRIPTION) VALUES ('USB Drive', '32GB USB flash drive');
INSERT INTO EBA_DEMO_MERCHANDISE (NAME, DESCRIPTION) VALUES ('Sticker Pack', 'Set of 10 custom stickers');
INSERT INTO EBA_DEMO_MERCHANDISE (NAME, DESCRIPTION) VALUES ('Hoodie', 'Soft fleece hoodie with zipper');
COMMIT;

