CREATE TABLE EBA_DEMO_MERCHANDISE
    (
    ID          NUMBER GENERATED ALWAYS AS IDENTITY ( START WITH 1 CACHE 20 ) ,
    NAME        VARCHAR2 (50) ,
    DESCRIPTION VARCHAR2 (200)
    )
    LOGGING ;

ALTER TABLE EBA_DEMO_MERCHANDISE
    ADD CONSTRAINT EBA_DEMO_MERCHANDISE_PK PRIMARY KEY ( ID )
    USING INDEX LOGGING ;

commit;

